openapi: 3.0.3
info:
  title: Hii Retail Business Unit Group Input API
  description: |
    Create, update and delete Business Unit Group data in Hii Retail services.
    A business unit group is a logical grouping of business units that share
    common configuration such as assortment, pricing, tax, or organizational structure.
  version: 1.0.0
  contact:
    name: Hii Retail
    url: https://developer.hiiretail.com

servers:
  - url: /api/v1/business-unit-group-input
    description: Business Unit Group Input API

paths:
  /api/v1/business-unit-groups:
    post:
      operationId: createBusinessUnitGroup
      summary: Create a new business unit group
      description: |
        Creates a new business unit group in Hii Retail. Returns 202 Accepted on success.
        Timestamps (created, modified) are set server-side.
      tags: [Business Unit Groups]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessUnitGroupInput'
            example:
              id: "bug-001"
              name: "Sweden Stores Assortment"
              type: ASSORTMENT
              status: ACTIVE
              description: "Assortment group for all Swedish retail stores"
              tags: ["sweden", "assortment", "retail"]
      responses:
        '202':
          description: Accepted — business unit group submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request — validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/v1/business-unit-groups/{businessUnitGroupId}:
    put:
      operationId: updateBusinessUnitGroup
      summary: Update an existing business unit group
      tags: [Business Unit Groups]
      parameters:
        - $ref: '#/components/parameters/businessUnitGroupId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessUnitGroupInput'
      responses:
        '202':
          description: Accepted — update submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Business unit group not found
    delete:
      operationId: deleteBusinessUnitGroup
      summary: Soft-delete a business unit group
      description: Sets the business unit group status to DELETED.
      tags: [Business Unit Groups]
      parameters:
        - $ref: '#/components/parameters/businessUnitGroupId'
      responses:
        '202':
          description: Accepted — deletion submitted for processing
        '401':
          description: Unauthorized
        '404':
          description: Business unit group not found

components:
  parameters:
    businessUnitGroupId:
      name: businessUnitGroupId
      in: path
      required: true
      schema:
        type: string
      description: The business unit group identifier

  schemas:
    BusinessUnitGroupInput:
      type: object
      required:
        - id
        - name
        - type
        - status
      properties:
        id:
          type: string
          description: External business unit group identifier
          example: "bug-001"
        correlationId:
          type: string
          description: ID for tracing an entity through the application
        name:
          type: string
          description: Display name of the business unit group
          example: "Sweden Stores Assortment"
        type:
          type: string
          enum: [ASSORTMENT, PRICING, TAX, CONFIGURATION, LEGAL_ENTITY, ORGANIZATIONAL]
          description: |
            Business unit group classification:
            - ASSORTMENT: Groups sharing the same product assortment
            - PRICING: Groups sharing the same pricing rules
            - TAX: Groups sharing the same tax configuration
            - CONFIGURATION: Groups sharing operational configuration
            - LEGAL_ENTITY: Groups representing a legal entity
            - ORGANIZATIONAL: Groups for organizational hierarchy
          example: ASSORTMENT
        status:
          type: string
          enum: [ACTIVE, DELETED]
          description: Entity lifecycle status
          example: ACTIVE
        description:
          type: string
          description: Detailed description of the business unit group
          example: "Assortment group for all Swedish retail stores"
        parentBusinessUnitGroupId:
          type: string
          description: Parent group ID for hierarchical grouping
        tags:
          type: array
          items:
            type: string
          description: Searchable classification tags
          example: ["sweden", "assortment", "retail"]
        version:
          type: integer
          description: Ever-increasing version integer (set server-side on update)

    AcceptedResponse:
      type: object
      properties:
        message:
          type: string
          example: "Request accepted for processing"
        id:
          type: string
          description: The entity ID

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: "Validation failed"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth2 JWT token from Hii Retail IAM

security:
  - bearerAuth: []
