openapi: 3.0.3
info:
  title: Hii Retail Item Input API
  description: |
    Create, update and delete Item data in Hii Retail services.
    The Item entity is the main entity for rapidly changing master data
    and is the base for most retail operations.
  version: 1.0.0
  contact:
    name: Hii Retail
    url: https://developer.hiiretail.com

servers:
  - url: /api/v1/item-input
    description: Item Input API

paths:
  /api/v1/items:
    post:
      operationId: createItem
      summary: Create a new item
      description: |
        Creates a new item in Hii Retail. Returns 202 Accepted on success.
        Timestamps (created, modified) are set server-side.
      tags: [Items]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
            example:
              id: "item-001"
              name: "Organic Whole Milk 1L"
              description: "Fresh organic whole milk, 1 litre"
              type: STOCK_ITEM
              status: ACTIVE
              salesUnitOfMeasurement: EA
              referencePriceUnitOfMeasurement: LTR
              referencePriceConversionFactor: 1.0
              availableInPos: true
              needsManualSending: false
              needsApproval: false
              needsLabelPrinting: true
              assortmentPolicyType: INCLUDED
              brand: "EcoFarm"
              netContent: 1.0
              tags: ["dairy", "organic", "milk"]
              businessUnitGroupId: "bug-001"
      responses:
        '202':
          description: Accepted — item submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request — validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/v1/items/{itemId}:
    put:
      operationId: updateItem
      summary: Update an existing item
      tags: [Items]
      parameters:
        - $ref: '#/components/parameters/itemId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
      responses:
        '202':
          description: Accepted — update submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Item not found
    delete:
      operationId: deleteItem
      summary: Soft-delete an item
      description: Sets the item status to DELETED.
      tags: [Items]
      parameters:
        - $ref: '#/components/parameters/itemId'
      responses:
        '202':
          description: Accepted — deletion submitted for processing
        '401':
          description: Unauthorized
        '404':
          description: Item not found

components:
  parameters:
    itemId:
      name: itemId
      in: path
      required: true
      schema:
        type: string
      description: The item identifier

  schemas:
    ItemInput:
      type: object
      required:
        - id
        - name
        - type
        - status
        - salesUnitOfMeasurement
        - referencePriceUnitOfMeasurement
        - referencePriceConversionFactor
        - availableInPos
        - needsManualSending
        - needsApproval
        - needsLabelPrinting
        - assortmentPolicyType
        - businessUnitGroupId
      properties:
        id:
          type: string
          description: External item identifier from ERP system
          example: "item-001"
        correlationId:
          type: string
          description: ID for tracing an entity through the application
        name:
          type: string
          description: Display name of the item
          example: "Organic Whole Milk 1L"
        description:
          type: string
          description: Detailed description of the item
        type:
          type: string
          enum: [STOCK_ITEM, SERVICE, BUNDLE, MODEL]
          description: |
            Item classification type:
            - STOCK_ITEM: Normal physical product (most common)
            - SERVICE: Non-physical service item
            - BUNDLE: Bundle of multiple products
            - MODEL: Model definition for related product variants
          example: STOCK_ITEM
        status:
          type: string
          enum: [ACTIVE, DELETED]
          description: Entity lifecycle status
          example: ACTIVE
        salesUnitOfMeasurement:
          type: string
          enum: [EA, KG, KRM, GRM, LTR, MLT, MTR, CMT, MMT, M2, M3]
          description: |
            Unit in which the item is sold:
            - EA: Each (piece)
            - KG: Kilogram
            - KRM: Kilogram (reference measure)
            - GRM: Gram
            - LTR: Litre
            - MLT: Millilitre
            - MTR: Metre
            - CMT: Centimetre
            - MMT: Millimetre
            - M2: Square metre
            - M3: Cubic metre
          example: EA
        referencePriceUnitOfMeasurement:
          type: string
          enum: [EA, KG, KRM, GRM, LTR, MLT, MTR, CMT, MMT, M2, M3]
          description: Unit used to calculate the reference price (price per unit)
          example: LTR
        referencePriceConversionFactor:
          type: number
          format: float
          description: Conversion factor for calculating price per unit based on reference measurement
          example: 1.0
        availableInPos:
          type: boolean
          description: Whether the item is available for POS operations
          default: true
          example: true
        needsManualSending:
          type: boolean
          description: Whether the item requires manual POS transmission
          example: false
        needsApproval:
          type: boolean
          description: Whether the item requires manual approval before distribution
          example: false
        needsLabelPrinting:
          type: boolean
          description: Whether the item requires label printing
          example: true
        assortmentPolicyType:
          type: string
          enum: [INCLUDED, EXCLUDED, LOCAL]
          description: Assortment assignment classification
          example: INCLUDED
        assortmentFrom:
          type: string
          format: date-time
          description: Start date for assortment validity
        assortmentTo:
          type: string
          format: date-time
          description: End date for assortment validity
        assortmentTags:
          type: array
          items:
            type: string
          description: Searchable tags describing assortment policy
        brand:
          type: string
          description: Product brand name
          example: "EcoFarm"
        netContent:
          type: number
          format: float
          description: Product net content quantity
          example: 1.0
        tags:
          type: array
          items:
            type: string
          description: Searchable product classification tags
          example: ["dairy", "organic", "milk"]
        itemCategoryId:
          type: string
          description: Associated item category identifier
        depositAndFeeRuleIds:
          type: array
          items:
            type: string
          description: References to deposit and fee rules (e.g. bottle deposits)
        images:
          type: array
          items:
            $ref: '#/components/schemas/ItemImage'
        additionalProperties:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalProperty'
          description: Customer-specific key-value pairs
        businessUnitGroupId:
          type: string
          description: Business unit group this item belongs to
          example: "bug-001"
        businessUnitIds:
          type: array
          items:
            type: string
          description: Specific business units this item is associated with
        version:
          type: integer
          description: Ever-increasing version integer (set server-side on update)

    ItemImage:
      type: object
      properties:
        url:
          type: string
          format: uri
        type:
          type: string
        sortOrder:
          type: integer

    AdditionalProperty:
      type: object
      required: [key, value]
      properties:
        key:
          type: string
        value:
          type: string

    AcceptedResponse:
      type: object
      properties:
        message:
          type: string
          example: "Request accepted for processing"
        id:
          type: string
          description: The entity ID

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: "Validation failed"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth2 JWT token from Hii Retail IAM

security:
  - bearerAuth: []
