openapi: 3.0.3
info:
  title: Hii Retail Item Category Input API
  description: |
    Create, update and delete Item Category data in Hii Retail services.
    Item categories organize products into a hierarchical classification
    structure for reporting, navigation, and business rules.
  version: 1.0.0
  contact:
    name: Hii Retail
    url: https://developer.hiiretail.com

servers:
  - url: /api/v1/item-category-input
    description: Item Category Input API

paths:
  /api/v1/item-categories:
    post:
      operationId: createItemCategory
      summary: Create a new item category
      description: |
        Creates a new item category in Hii Retail. Returns 202 Accepted on success.
        Timestamps (created, modified) are set server-side.
      tags: [Item Categories]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCategoryInput'
            example:
              id: "cat-dairy-001"
              name: "Dairy Products"
              status: ACTIVE
              businessUnitGroupId: "bug-001"
              description: "Milk, cheese, yoghurt and other dairy products"
              type: USER_DEFINED
              sortOrder: 100
              tags: ["dairy", "chilled"]
      responses:
        '202':
          description: Accepted — item category submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request — validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/v1/item-categories/{categoryId}:
    put:
      operationId: updateItemCategory
      summary: Update an existing item category
      tags: [Item Categories]
      parameters:
        - $ref: '#/components/parameters/categoryId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemCategoryInput'
      responses:
        '202':
          description: Accepted — update submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Item category not found
    delete:
      operationId: deleteItemCategory
      summary: Soft-delete an item category
      description: Sets the item category status to DELETED.
      tags: [Item Categories]
      parameters:
        - $ref: '#/components/parameters/categoryId'
      responses:
        '202':
          description: Accepted — deletion submitted for processing
        '401':
          description: Unauthorized
        '404':
          description: Item category not found

components:
  parameters:
    categoryId:
      name: categoryId
      in: path
      required: true
      schema:
        type: string
      description: The item category identifier

  schemas:
    ItemCategoryInput:
      type: object
      required:
        - id
        - name
        - status
        - businessUnitGroupId
      properties:
        id:
          type: string
          description: External item category identifier
          example: "cat-dairy-001"
        correlationId:
          type: string
          description: ID for tracing an entity through the application
        name:
          type: string
          description: Display name of the category
          example: "Dairy Products"
        status:
          type: string
          enum: [ACTIVE, DELETED]
          description: Entity lifecycle status
          example: ACTIVE
        businessUnitGroupId:
          type: string
          description: Business unit group this category belongs to
          example: "bug-001"
        description:
          type: string
          description: Detailed description of the category
          example: "Milk, cheese, yoghurt and other dairy products"
        parentCategoryId:
          type: string
          description: Parent category ID for hierarchical categorization
        type:
          type: string
          enum: [USER_DEFINED, GS1_GPC_BRICK, GS1_GPC_CLASS, GS1_GPC_FAMILY, GS1_GPC_SEGMENT]
          description: |
            Category classification type:
            - USER_DEFINED: Custom retailer-defined category
            - GS1_GPC_BRICK: GS1 Global Product Classification brick level
            - GS1_GPC_CLASS: GS1 GPC class level
            - GS1_GPC_FAMILY: GS1 GPC family level
            - GS1_GPC_SEGMENT: GS1 GPC segment level
          example: USER_DEFINED
        sortOrder:
          type: integer
          description: Display sort order within the parent category
          example: 100
        tags:
          type: array
          items:
            type: string
          description: Searchable classification tags
          example: ["dairy", "chilled"]
        version:
          type: integer
          description: Ever-increasing version integer (set server-side on update)

    AcceptedResponse:
      type: object
      properties:
        message:
          type: string
          example: "Request accepted for processing"
        id:
          type: string
          description: The entity ID

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: "Validation failed"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth2 JWT token from Hii Retail IAM

security:
  - bearerAuth: []
