openapi: 3.0.3
info:
  title: Hii Retail Item Identifier Input API
  description: |
    Create, update and delete Item Identifiers in Hii Retail services.
    An Item Identifier represents an identification code (GTIN, PLU, QR, etc.)
    linked to an item. GTINs are validated for correct length and check digit.
    Each GTIN must be unique within a tenant.
  version: 1.0.0
  contact:
    name: Hii Retail
    url: https://developer.hiiretail.com

servers:
  - url: /api/v1/item-identifier-input
    description: Item Identifier Input API

paths:
  /api/v1/item-identifiers:
    post:
      operationId: createItemIdentifier
      summary: Create a new item identifier
      description: |
        Creates an item identifier (barcode, PLU, QR code, etc.) linked to an item.
        GTIN identifiers are validated for correct length and check digit.
        Duplicate GTINs within a tenant are rejected. Returns 202 Accepted on success.
      tags: [Item Identifiers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemIdentifierInput'
            example:
              id: "ident-001"
              itemId: "item-001"
              value: "7310865085801"
              type: GTIN13
              status: ACTIVE
              businessUnitGroupId: "bug-001"
      responses:
        '202':
          description: Accepted — identifier submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request — validation failed (e.g. invalid GTIN check digit)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/v1/item-identifiers/{identifierId}:
    put:
      operationId: updateItemIdentifier
      summary: Update an existing item identifier
      tags: [Item Identifiers]
      parameters:
        - $ref: '#/components/parameters/identifierId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemIdentifierInput'
      responses:
        '202':
          description: Accepted — update submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Identifier not found
    delete:
      operationId: deleteItemIdentifier
      summary: Delete an item identifier
      description: Sets the identifier status to DELETED.
      tags: [Item Identifiers]
      parameters:
        - $ref: '#/components/parameters/identifierId'
      responses:
        '202':
          description: Accepted — deletion submitted for processing
        '401':
          description: Unauthorized
        '404':
          description: Identifier not found

components:
  parameters:
    identifierId:
      name: identifierId
      in: path
      required: true
      schema:
        type: string
      description: The item identifier ID

  schemas:
    ItemIdentifierInput:
      type: object
      required:
        - id
        - itemId
        - value
        - type
        - status
        - businessUnitGroupId
      properties:
        id:
          type: string
          description: External identifier ID
          example: "ident-001"
        correlationId:
          type: string
          description: ID for tracing through the application
        itemId:
          type: string
          description: The item this identifier belongs to
          example: "item-001"
        value:
          type: string
          description: |
            The actual identification code value.
            For GTIN types: must be correct length with valid check digit.
            For PLU: typically 4-5 digit numeric code.
            For QR/ECC200: can be any string value.
          example: "7310865085801"
        type:
          type: string
          enum:
            - GTIN8
            - GTIN12
            - GTIN13
            - GTIN14
            - GTIN
            - PLU
            - SKU
            - QR
            - ECC140
            - ECC200
            - ISBN
            - RFID
            - ISSN
            - NONSTANDARD
            - UUID
          description: |
            The identifier type:
            - GTIN8/12/13/14: GS1 Global Trade Item Number (validated)
            - GTIN: Generic GTIN (auto-detected length)
            - PLU: Price Look-Up code
            - SKU: Stock Keeping Unit
            - QR: QR code
            - ECC200: DataMatrix barcode (preferred 2D)
            - ECC140: DataMatrix legacy format
            - ISBN/ISSN: Publication identifiers
            - RFID: Radio-frequency identification
            - NONSTANDARD: Non-standard code
            - UUID: Universal unique identifier
          example: GTIN13
        status:
          type: string
          enum: [ACTIVE, DELETED]
          description: Identifier lifecycle status
          example: ACTIVE
        additionalProperties:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalProperty'
          description: Customer-specific key-value pairs
        businessUnitGroupId:
          type: string
          description: Business unit group this identifier belongs to
          example: "bug-001"
        businessUnitIds:
          type: array
          items:
            type: string
          description: Specific business units
        version:
          type: integer
          description: Ever-increasing version integer

    AdditionalProperty:
      type: object
      required: [key, value]
      properties:
        key:
          type: string
        value:
          type: string

    AcceptedResponse:
      type: object
      properties:
        message:
          type: string
          example: "Request accepted for processing"
        id:
          type: string

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
