openapi: 3.0.3
info:
  title: Hii Retail Price Specification Input API
  description: |
    Create or update Price Specification data in Hii Retail services.
    A price specification defines the monetary value for an item,
    including currency, tax rules, and validity periods.
  version: 1.0.0
  contact:
    name: Hii Retail
    url: https://developer.hiiretail.com

servers:
  - url: /api/v1/price-specification-input
    description: Price Specification Input API

paths:
  /api/v1/price-specifications:
    post:
      operationId: createPriceSpecification
      summary: Create a new price specification
      description: |
        Creates a price specification for an item. Returns 202 Accepted on success.
        The item referenced by itemId must exist.
      tags: [Price Specifications]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceSpecificationInput'
            example:
              id: "price-001"
              itemId: "item-001"
              type: NORMAL
              value: 2.49
              currencyId: "SEK"
              taxableGroupId: "tax-food-12"
              validFrom: "2025-01-01T00:00:00Z"
              status: ACTIVE
              excludingTax: false
              businessUnitGroupId: "bug-001"
      responses:
        '202':
          description: Accepted — price specification submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request — validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/v1/price-specifications/{priceSpecId}:
    put:
      operationId: updatePriceSpecification
      summary: Update an existing price specification
      tags: [Price Specifications]
      parameters:
        - $ref: '#/components/parameters/priceSpecId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceSpecificationInput'
      responses:
        '202':
          description: Accepted — update submitted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptedResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '404':
          description: Price specification not found
    delete:
      operationId: deletePriceSpecification
      summary: Delete a price specification
      tags: [Price Specifications]
      parameters:
        - $ref: '#/components/parameters/priceSpecId'
      responses:
        '202':
          description: Accepted — deletion submitted for processing
        '401':
          description: Unauthorized
        '404':
          description: Price specification not found

components:
  parameters:
    priceSpecId:
      name: priceSpecId
      in: path
      required: true
      schema:
        type: string
      description: The price specification identifier

  schemas:
    PriceSpecificationInput:
      type: object
      required:
        - id
        - itemId
        - type
        - value
        - currencyId
        - validFrom
        - status
        - businessUnitGroupId
      properties:
        id:
          type: string
          description: External price specification identifier
          example: "price-001"
        correlationId:
          type: string
          description: ID for tracing through the application
        itemId:
          type: string
          description: Reference to the item this price belongs to
          example: "item-001"
        type:
          type: string
          enum: [NORMAL, CAMPAIGN, COST, COMPETITOR, RECOMMENDED]
          description: |
            The price type:
            - NORMAL: Standard retail price
            - CAMPAIGN: Promotional campaign price
            - COST: Cost/purchase price
            - COMPETITOR: Competitor reference price
            - RECOMMENDED: Manufacturer recommended price
          example: NORMAL
        value:
          type: number
          format: float
          description: The price value including taxes (unless excludingTax is true)
          example: 2.49
        minPrice:
          type: number
          format: float
          description: The lowest price if this is a price range
        maxPrice:
          type: number
          format: float
          description: The highest price if this is a price range
        currencyId:
          type: string
          description: ISO 4217 currency code
          example: "SEK"
        taxableGroupId:
          type: string
          description: ID of the taxable group for tax calculation
          example: "tax-food-12"
        validFrom:
          type: string
          format: date-time
          description: Date and time the price becomes valid
          example: "2025-01-01T00:00:00Z"
        validTo:
          type: string
          format: date-time
          description: Date and time the price expires (null = valid indefinitely)
        promotionId:
          type: string
          description: Promotion ID if this is a promotion price
        discountIds:
          type: array
          items:
            type: string
          description: List of applicable discount IDs
        status:
          type: string
          enum: [ACTIVE, DELETED]
          description: Price specification lifecycle status
          example: ACTIVE
        isMandatory:
          type: boolean
          description: Flag for top-down price inheritance override
        excludingTax:
          type: boolean
          description: Whether the value excludes VAT/taxes
          default: false
          example: false
        additionalProperties:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalProperty'
          description: Customer-specific key-value pairs
        businessUnitGroupId:
          type: string
          description: Business unit group this price belongs to
          example: "bug-001"
        businessUnitIds:
          type: array
          items:
            type: string
          description: Specific business units this price is associated with
        version:
          type: integer
          description: Ever-increasing version integer

    AdditionalProperty:
      type: object
      required: [key, value]
      properties:
        key:
          type: string
        value:
          type: string

    AcceptedResponse:
      type: object
      properties:
        message:
          type: string
          example: "Request accepted for processing"
        id:
          type: string

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
